version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: sungrohRyu
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ciae
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
